server:
  port: 8003

spring:
  datasource:
    url: jdbc:mysql://prod-db-server:3306/dlp_auth_prod?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: prod_user
    password: prod_password

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    # Make database connection optional for testing
    defer-datasource-initialization: true
    
  # Make application start even if database is not available
  sql:
    init:
      continue-on-error: true

  security:
    oauth2:
      client:
        registration:
          azure:
            client-id: ${AZURE_CLIENT_ID}
            client-secret: ${AZURE_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
              - offline_access
              - https://graph.microsoft.com/User.Read
              - https://graph.microsoft.com/Mail.Read
              - https://graph.microsoft.com/Mail.ReadWrite
            authorization-grant-type: authorization_code
            redirect-uri: ${REDIRECT_URI:http://localhost:8003/login/oauth2/code/azure}
            client-name: Azure
        provider:
          azure:
            issuer-uri: https://login.microsoftonline.com/${AZURE_TENANT_ID:00fbdbac-bf96-4ddc-8685-01819c5c546d}/v2.0
            token-uri: https://login.microsoftonline.com/${AZURE_TENANT_ID:00fbdbac-bf96-4ddc-8685-01819c5c546d}/oauth2/v2.0/token
            user-info-uri: https://graph.microsoft.com/oidc/userinfo

logging:
  level:
    root: WARN
    org.springframework.security: WARN
    com.yourapp: INFO
