spring:
  security:
    oauth2:
      client:
        registration:
          azure:
            client-id: ${AZURE_CLIENT_ID}
            client-secret: ${AZURE_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
              - offline_access
              - https://graph.microsoft.com/User.Read
              - https://graph.microsoft.com/Mail.Read
              - https://graph.microsoft.com/Mail.ReadWrite
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8000/login/oauth2/code/azure
            client-name: Azure
        provider:
          azure:
            authorization-uri: https://login.microsoftonline.com/${AZURE_TENANT_ID:00fbdbac-bf96-4ddc-8685-01819c5c546d}/oauth2/v2.0/authorize
            token-uri: https://login.microsoftonline.com/${AZURE_TENANT_ID:00fbdbac-bf96-4ddc-8685-01819c5c546d}/oauth2/v2.0/token
            user-info-uri: https://graph.microsoft.com/oidc/userinfo
            jwk-set-uri: https://login.microsoftonline.com/${AZURE_TENANT_ID:00fbdbac-bf96-4ddc-8685-01819c5c546d}/discovery/v2.0/keys
            user-name-attribute: sub

  jackson:
    serialization:
      indent_output: true

logging:
  level:
    root: INFO
    org.springframework.security: INFO
    com.dlpauth: DEBUG

server:
  port: 8000
