name: CD - Deploy to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-artifact:
    name: Build Artifact
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven using staging profile
        run: mvn clean install -DskipTests -Dspring.profiles.active=staging
        working-directory: dlp-auth

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dlp-auth-artifact
          path: dlp-auth/target/*.jar

  deploy-staging:
    name: Deploy to Staging
    needs: build-artifact
    runs-on: ubuntu-latest

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: dlp-auth-artifact

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App - Staging
        uses: azure/webapps-deploy@v3
        with:
          app-name: dlp-auth
          slot-name: staging
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: '*.jar'

  
