name: Build and Deploy Spring Boot App to Azure Web App

on:
  push:
    branches:
      - main  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install -DskipTests
        working-directory: dlp-auth

      - name: Upload Artifact for Deployment
        uses: actions/upload-artifact@v4
        with:
          name: dlp-auth-artifact
          path: dlp-auth/target/*.jar

      - name: 'Azure Login'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App (Staging Slot)
        uses: azure/webapps-deploy@v3
        with:
          app-name: dlp-auth
          slot-name: staging
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: dlp-auth/target/*.jar
